<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSad4cfv\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSad4cfv/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSad4cfv.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSad4cfv\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerSad4cfv\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Sad4cfv',
    'container.build_id' => '8a4a3381',
    'container.build_time' => 1525604458,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSad4cfv');
