<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCx2qzca\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCx2qzca/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCx2qzca.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCx2qzca\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCx2qzca\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Cx2qzca',
    'container.build_id' => '276a3c72',
    'container.build_time' => 1525604655,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCx2qzca');
